
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="/Capstone/login_final.css">
		<link rel="stylesheet" type="text/css" href="/Capstone/info.css">
	</head>
	<body background = "/Capstone/images/Bckgrnd1.jpg">
		<form action = "redirectPortfolio.php" method = "post">
			<input type="submit" id = "cur_port" class="button" value="Current Portfolio">
		</form>
		<form action = "visualizations.php" method = "post">
			<input type="submit" id = "int_visual" class="button" value="Portfolio Dashboards">
		</form>		
		<input type="submit" id = "more_info" class="button" value="More Information">
		<form action = "logout.php" method = "post">
			<input type = "submit" id = "log_out" class = "button" value = "Logout"><br><br>
		</form>
		<p id = "stock">
			<b>Stock</b>
			<br>A stock is a type of security that signifies ownership in a corporation and represents a claim on part of the corporation's assets and earnings.
			<br>There are two main types of stock: common and preferred.
		</p>
		<p id = "bond">
			<b>Bonds</b>
			<br>An individual bond is a piece of a massive loan. That’s because the size of these entities requires them to borrow money from more than one source.
		</p>
		<p id = "dividend">
			<b>Dividend</b>
			<br>A dividend is a distribution of a portion of a company's earnings, decided by the board of directors, paid to a class of its shareholders.
		</p>
		<p id = "portfolio">
			<b>Portfolio</b>
			<br>A portfolio is a combination of investment in different types of securities such as stocks, bonds etc.
		</p>
		<p id = "dogs">
			<b>Dogs of the Dow</b>
			<br>The Dogs of the Dow is an investment strategy popularized by Michael B. 
			O'Higgins in 1991, which proposes that an investor annually select for investment the ten Dow Jones Industrial Average (DJIA) <br>stocks whose dividend is the highest fraction of their price.
		</p>
		<p id = "alpha">
			<b>Alpha</b>
			<br>Alpha is used in finance as a measure of performance. 
			Alpha, often considered the active return on an investment, gauges the performance of an investment against a market index or benchmark which is considered to represent the market's movement as a whole.
		</p>
		<p id = "beta">
			<b>Beta</b>
			<br>Beta is a measure of a stock's volatility in relation to the market.
		</p>
		<p id = "ask">
			<b>Ask</b>
			<br>The ask price is the lowest price a seller of a stock is willing to accept for a share of that given stock.
		</p>
		<p id = "bid">
			<b>Bid</b>
			<br>A bid is an offer made by an investor, trader or dealer to buy a security, commodity or currency. 
		</p>
		<p id = "ft">
			<b>Fundamental vs Technical Analysis</b>
			<br>Fundamental analysis aims to find the enterprise value of the company. This means arriving at its Intrinsic price. This kind of analysis uses Economic factors.
			<br>Technical analysis is a method of evaluating Securities. But the entire game here is dependent upon the statistics generated by the market. Charts and patterns are the Bread and Butter of <br>technical analysis.
		</p>
	</body>
</html>